server:
  port: 8070
  servlet:
    context-path: /SpringBoot-CheckPort


dept:
  is:
    enable: 0

user:
  enable: 1
  open: 2

logging:
  config: classpath:log4j2-Roger.xml
  charset:
    file: utf-8
    console: UTF-8